# Generated by Django 6.0.4 on 2026-04-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_guests', models.PositiveSmallIntegerField(default=2)),
                ('size_sqm', models.PositiveIntegerField(default=30)),
                ('bed_type', models.CharField(default='King', max_length=80)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('cover_image', models.URLField(max_length=500)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
