# Generated by Django 6.0.4 on 2026-04-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='garden_facing',
            field=models.BooleanField(default=False, help_text='Faces garden / courtyard'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_ac',
            field=models.BooleanField(default=True, help_text='Air-conditioned room'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='washroom_type',
            field=models.CharField(choices=[('western', 'Western'), ('indian', 'Indian')], default='western', max_length=20),
        ),
    ]
