# Generated by Django 6.0.4 on 2026-04-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_details',
            field=models.JSONField(blank=True, default=list, help_text='List of {full_name, phone, email} per guest.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('qr', 'QR code')], max_length=16),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='booking_payments/%Y/%m/'),
        ),
    ]
