# Generated by Django 6.0.4 on 2026-04-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHomeContent',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('hero_carousel', models.JSONField(blank=True, default=list)),
                ('home_gallery', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home page content',
                'verbose_name_plural': 'Home page content',
            },
        ),
    ]
